from playwright.sync_api import sync_playwright

def verify_app():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        
        # Navigate to homepage
        print("Navigating to home...")
        page.goto("http://localhost:5173/")
        page.wait_for_timeout(3000) # Wait for products to load (mocking firebase delay)
        page.screenshot(path="verification/1_home.png")
        print("Home screenshot taken.")
        
        # Navigate to category
        print("Navigating to category...")
        page.goto("http://localhost:5173/category/ropa")
        page.wait_for_timeout(3000)
        page.screenshot(path="verification/2_category.png")
        print("Category screenshot taken.")

        # Navigate to detail (assuming a product exists or clicking one if found)
        # Since we don't know exact IDs generated by Firestore without querying, 
        # we can try to click the first "Ver Detalle" link found on home.
        print("Navigating to detail...")
        page.goto("http://localhost:5173/")
        page.wait_for_timeout(3000)
        
        try:
            # Click first product detail
            page.click("text=Ver Detalle")
            page.wait_for_timeout(3000)
            page.screenshot(path="verification/3_detail.png")
            print("Detail screenshot taken.")
            
            # Add to cart
            print("Adding to cart...")
            page.click("text=Agregar al Carrito")
            page.wait_for_timeout(1000)
            page.screenshot(path="verification/4_added_to_cart.png")
            
            # Go to cart
            print("Going to cart...")
            page.goto("http://localhost:5173/cart")
            page.wait_for_timeout(1000)
            page.screenshot(path="verification/5_cart.png")
            
            # Go to checkout
            print("Going to checkout...")
            page.click("text=Terminar Compra")
            page.wait_for_timeout(1000)
            page.screenshot(path="verification/6_checkout.png")
            
        except Exception as e:
            print(f"Error interacting with elements: {e}")
            page.screenshot(path="verification/error.png")

        browser.close()

if __name__ == "__main__":
    verify_app()
